# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.0
maven_group = net.manahoz.litra_elytra
archives_name = litra_elytra
enabled_platforms = fabric,forge

# Minecraft properties
minecraft_version = 1.20.1
yarn_mappings = 1.20.1+build.10

# Dependencies
fabric_loader_version = 0.19.5
fabric_api_version = 0.92.12+1.20.1
forge_version = 1.20.1-47.4.22

midnightlib_fabric_version = 1.9.3+1.20.1-fabric
midnightlib_forge_version = 1.9.2+1.20.1-forge
modmenu_version = 7.2.2
