modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "litra_elytra"
version = "${version}"
displayName = "Litra Elytra"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.litra_elytra]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.litra_elytra]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.litra_elytra]]
modId = "midnightlib"
mandatory = true
versionRange = "[1.9.3,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "litra_elytra.mixins.json"
